FROM golang:1.13-alpine as build-env

WORKDIR /exago

COPY go.mod .
COPY go.sum .

FROM build-env

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.1

COPY . .
WORKDIR /exago/src/consumer

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install -a -tags netgo -ldflags '-w -extldflags "-static"' ./

ENTRYPOINT ["/go/bin/consumer"]