FROM golang:1.13-alpine as build-env

WORKDIR /exago

ENV PORT 8080

COPY . .
FROM build-env AS server-builder
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install -a -tags netgo -ldflags '-w -extldflags "-static"' ./cmd/api

EXPOSE ${PORT}

FROM gcr.io/distroless/base
COPY --from=server-builder /go/bin/api /
ENTRYPOINT ["/api"]
