ARG GO_VERSION=alpine
FROM golang:${GO_VERSION}

WORKDIR /exago

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install -a -tags netgo -ldflags "-X main.GoVersion=$GO_VERSION" ./cmd/consumer

ENTRYPOINT ["/go/bin/consumer"]