FROM golang:1.13 as build-env

WORKDIR /exago

ENV PORT 8080

COPY go.mod .
COPY go.sum .

FROM build-env AS server-builder
COPY src/api .
WORKDIR /exago/src/api
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install -a -tags netgo -ldflags '-w -extldflags "-static"' ./

EXPOSE ${PORT}

FROM gcr.io/distroless/base
COPY --from=server-builder /go/bin/api /
ENTRYPOINT ["/api"]
